source 'https://rubygems.org'

gem 'github-pages'
gem 'bourbon'
gem 'coffee-script'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-haml'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'neat'
gem 'sass'
gem 'uglifier'
gem 'proteus-kits', '0.3'
gem 'mini_magick', '4.3.6'
gem 'jekyll-minimagick', '0.0.3'