source 'https://rubygems.org'

gem 'bourbon'
gem 'coffee-script'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-assets-autoprefixer'
gem 'jekyll-haml'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'neat'
gem 'sass'
gem 'uglifier'
gem 'jekyll-redirect-from'